name: custom_cam
description: This package project offers an easy way to get camera functionality with a custom UI.
version: 1.0.3
homepage: https://github.com/marcelosolorzano/custom_cam

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  camera: ^0.10.3
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.1
  path_provider: ^2.0.12
  video_player: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - packages/custom_cam/assets/CustomIcons.ttf

  fonts:
    - family: CustomIcons
      fonts:
        - asset: packages/custom_cam/assets/CustomIcons.ttf

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
